name: my-actions

runs:
  using: 'composite'
  steps:
    - name: set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm' # or 'yarn'
        ache-dependency-path: app/node/package-lock.json