name: "node"
description: "node"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: pwd
      shell: bash
    - uses: actions/cache@v3
      id: node_modules_cache_id
      env:
        cache-name: cache-node-modules
      with:
        path: "app/node/node_modules"
        key: ${{ env.cache-name }}-${{ hashFiles('app/node/package-lock.json') }}-1
    - run: echo '${{ toJSON(steps.node_modules_cache_id.outputs) }}'
      shell: bash
    - if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: app/node
      run: npm install
