name: check

on:
  push:
  workflow_dispatch:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo ${{ github.action }} ${{ github.actor }}
      # - name: success
      #   if: ${{ success() }}
      #   run: echo 'success'
      # - name: success
      #   if: ${{ failure() }}
      #   run: echo 'failure'
