name: check

on:
  push:

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: step1
        if: ${{ github.action == 'push'}}
        run: echo ${{ github.action }} ${{ github.actor }}
      - name: success
        if: ${{ success() }}
        run: echo 'success'
      - name: success
        if: ${{ failure() }}
        run: echo 'failure'
