name: Node Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/node
      - name: jest
        run: |
          ls -la */*
          cd app/node
          ls -la */*
          npm run test