name: Node Test

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: app/node

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4.0
        ports:
          - 27017:27017
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run test suite
      run: npm run test 
