name: Node Test

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: app/node

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:4.4.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: pass
          MONGO_INITDB_DATABASE: prm_mongo
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: test
        uses: actions/setup-node@v2
        with:
            node-version: "14"
        run: |
          npm install
          npm run test
          npm run mongo